FROM --platform=$TARGETPLATFORM staneee/ubuntu:22.04

RUN apt-get update \
  && source /etc/os-release \
  && wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && rm packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install --no-install-recommends -y powershell \
  && apt-get dist-upgrade -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*


ENTRYPOINT /bin/bash
