FROM --platform=$TARGETPLATFORM openvpn/openvpn-as:3.0.1-84b60e70-Ubuntu24

RUN apt-get update \
    && apt-get install -y zip unzip vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

# copy scripts
COPY ./scripts/  /

# chmod +x scripts
RUN chmod +x /egg.sh

ENTRYPOINT /egg.sh \
    && exec /docker-entrypoint.sh