FROM --platform=$TARGETPLATFORM gitea/runner-images:ubuntu-20.04-slim


RUN apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    apt-transport-https \
    gnupg2 \
    software-properties-common \
    zip \
    && wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt update \
    && apt install -y powershell \
    && apt-get clean
    

