FROM --platform=$TARGETPLATFORM mcr.microsoft.com/dotnet/sdk:6.0-focal AS base


# 安装fontconfig库，用于Pdf导出,安装gdi+ 用于excel
RUN apt-get update \
    && apt-get install -y fontconfig libgdiplus zip wget \
    && apt-get clean \
    && ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll

