FROM --platform=$TARGETPLATFORM staneee/powershell:lts-ubuntu-22.04

# buildx args
ARG VERSION_STRING=5:27.3.1-1~ubuntu.22.04~jammy

COPY ./docker-install.sh /root/docker-install.sh

RUN /bin/bash /root/docker-install.sh "${VERSION_STRING}"
