FROM --platform=$TARGETPLATFORM staneee/powershell:lts-ubuntu-22.04-docker

# install nodejs
RUN apt-get update \
    && apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get update \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 
    
RUN npm install -g yarn

ENTRYPOINT /bin/bash